[package]
name = "Conway"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.219"
serde_json = "1.0"
iced = { version = "0.13.1", features = [
    "svg",
    "wgpu",
    "tokio",
    "canvas",
    "image",
] }
rand = "0.8.5"
image = "0.25.5"
